version: '3'

services:
  coredns:
    image: coredns/coredns
    restart: always
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./Corefile:/etc/coredns/Corefile
      - ./dnsconf:/etc/coredns/
