version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: dockersqltest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - .:/app
    working_dir: /app
    environment:
      MYSQL_ROOT_PASSWORD: kali
