version: '3'
services:
  jellyfin:
    #image: lscr.io/linuxserver/jellyfin:latest
    image: jellyfin/jellyfin
    user: 1000:1000
    container_name: jellyfin
    volumes:
      - ./config:/config
      - ./cache:/cache
      # - /home/harsha/ITProTv:/data/tvshows
      # - /home/harsha/torrents:/data/torrents
      # - /home/harsha/swa:/data/swa
      - ./movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      # - 1900:1900/udp #optional
    runtime: nvidia  # Add this line to specify the Nvidia runtime
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
